/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    Pet: { id: number; name: string; tag?: string };
    Pets: components["schemas"]["Pet"][];
    Error: { code: number; message: string };
  };
}
