/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    /**
     * A pet.
     */
    Pet: components["schemas"]["NewPet"] & { id: number };
    /**
     * A new pet.
     */
    NewPet: { name: string; tag?: string };
    /**
     * A discriminator example.
     */
    CatOrDog: components["schemas"]["Cat"] | components["schemas"]["Dog"];
    /**
     * A cat, meow.
     */
    Cat: { type: string; breed: "labrador" | "carlin" | "beagle" };
    /**
     * A dog, wooof.
     */
    Dog: { type: string; breed: "saimois" | "bengal" | "british shorthair" };
    /**
     * An error :(
     */
    Error: { code: number; message: string };
    /**
     * Request description
     */
    Request: { action?: ("create" | "read" | "update" | "delete")[] };
  };
}
